Changed .ps1 and .sh scripts.
SkylineCommunications/generate-tls-certificates pull request #14
Opened 2024-01-08 08:42 UTC by FlavioJA

-Refactored scripts to improve readability.
-Added functionality to load rootCA.

2024-01-08 13:36 UTC, SeppeDejonckheere requested changes

2024-01-08 16:08 UTC, FlavioJA commented on generate-certificates.ps1
> +        return [RootCA]::new($rootCAcrt, $rootCAkey)
Added support to specify the password.

2024-01-08 16:10 UTC, FlavioJA commented on generate-certificates.ps1
> +		   & "$openssl" "x509" "-req" "-CA" $rootCAcrt "-CAkey" $rootCAkey "-in" "$i.csr" "-out" "$i.crt_signed" "-days" "$Validity" "-CAcreateserial" "-passin" "pass:$Password" "-extfile" "$i.conf"
Passwords are only being generated in case the user uses an existing rootCA.

2024-01-08 16:10 UTC, FlavioJA commented on generate-certificates.ps1
> +		   # Log the certificates for this node (for debugging purposes)
Not Implemented

2024-01-08 17:04 UTC, FlavioJA commented on generate-certificates.sh
> +  echo 'Generating new Root CA certificate'
Added else block.

2024-01-08 17:04 UTC, FlavioJA commented on generate-certificates.sh
> +  echo "Creating Root CA truststore (JKS)"
Not Implemented

2024-01-08 17:10 UTC, FlavioJA commented on generate-certificates.sh
> +    keytool -keystore $i-node-keystore.jks -alias rootCA -importcert -file rootCA.crt -keypass $pwd -storepass $pwd -noprompt
Fixed

2024-01-08 17:10 UTC, FlavioJA commented on generate-certificates.sh
> +    openssl x509 -req -CA rootCA.crt -CAkey rootCA.key -in $i.csr -out $i.crt_signed -days $validity -CAcreateserial -passin pass:$pwd -extfile "${i}.conf"
Added support to provide pwd for rootCA

2024-01-10 07:22 UTC, SeppeDejonckheere approved these changes

2024-01-10 07:23 UTC, merged